[default]
log_file=mymon.log
# Panic 0
# Fatal 1
# Error 2
# Warn 3
# Info 4
# Debug 5
log_level=5

falcon_client=http://127.0.0.1:1988/v1/push

#自定义endpoint
endpoint=

[memcache]
port=11211;11212